steps:
- command: echo "hi there! 1234567891133qwerertyutrertsssssssssy"
- command: buildkite-agent annotate --context "append test" "<img src="https://upload.wikimedia.org/wikipedia/commons/1/16/HDRI_Sample_Scene_Balls_%28JPEG-HDR%29.jpg"> This is a test /n "
- command: buildkite-agent annotate --context "append test"  --append "/n This is append test"
- command: buildkite-agent annotate --context "append test"  --append "/n This is append test completed"
