env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: 'rt://tf-trial/workspaces/jfrog-ws1/test.txt'
  BUILDKITE_ARTIFACTORY_URL: 'https://personaluse4.jfrog.io/artifactory'
  BUILDKITE_ARTIFACTORY_USER: 'athreya'
  BUILDKITE_ARTIFACTORY_PASSWORD: 'Srinivas@24'

steps:
- command: echo "hello world" > test.txt
  plugins:
  - artifacts#v1.9.3:
      upload: "test.txt"
