env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: 'rt://tf-trial/workspaces/jfrog-ws1/test.txt'
  BUILDKITE_ARTIFACTORY_URL: 'https://personaluse4.jfrog.io/artifactory'
  BUILDKITE_ARTIFACTORY_USER: 'athreya'
  BUILDKITE_ARTIFACTORY_PASSWORD: 'Srinivas@24'
  $$BUILDKITE_ARTIFACT_PATHS: 'https://personaluse4.jfrog.io/artifactory/tf-trial/workspaces/jfrog-ws1/'

steps:
- label: "Perform task every 10 seconds for 1 minute"
  command: |
    for i in {1..6}
    do
       echo "Task $i"
       sleep 10
    done

