env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: 'rt://tf-trial/workspaces/jfrog-ws1/test.txt'
  BUILDKITE_ARTIFACTORY_URL: 'https://personaluse4.jfrog.io/artifactory'
  BUILDKITE_ARTIFACTORY_USER: 'athreya'
  BUILDKITE_ARTIFACTORY_PASSWORD: 'Srinivas@24'

steps:
- command: cat test-download.txt
  plugins:
  - artifacts#v1.9.3:
      download:
      - from: "test.txt"
        to: "test-download.txt"
        build: "018f2f87-2e5f-4ae2-aec6-c548c5be7ad1"
