# env:
#   BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: 'rt://tf-trial/workspaces/jfrog-ws1/test.txt'
#   BUILDKITE_ARTIFACTORY_URL: 'https://personaluse4.jfrog.io/artifactory'
#   BUILDKITE_ARTIFACTORY_USER: 'athreya'
#   BUILDKITE_ARTIFACTORY_PASSWORD: 'Srinivas@24'
#   $$BUILDKITE_ARTIFACT_PATHS: 'https://personaluse4.jfrog.io/artifactory/tf-trial/workspaces/jfrog-ws1/'

# steps:
# - label: "Graceful Termination Test"
#   command: |
#     trap "echo 'This command indicates that we Received a SIGTERM and Ideally we should starting graceful shutdown... check the signal time from here'; sleep 90; echo 'Graceful shutdown complete.'" SIGTERM
#     echo "SSatrting a process that runs for 90 seconds to check"
#     sleep 90
#     echo "Long-running process completed."

steps:
- label: "job retry vs rebuild times test :rocket:"
  command: echo "this is a test for rebuild and retry $BUILDKITE_BUILD_ID and Job ID $BUILDKITE_JOB_ID"
